
[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font Mono"

[window]
decorations = "None"
opacity = 1

[window.padding]
x = 3
y = 3

[general]
import = ["/home/sirmax/.config/alacritty/riot.toml"]
