[core]
  editor = nvim
[alias]
	lgp = log --graph --oneline --all
  lg = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative
  lo = log --oneline
[init]
  defaultBranch = main
[commit]
	gpgsign = true

[submodule]
	recurse = true
[push]
	recurseSubmodules = on-demand
  autoSetupRemote = true

[merge]
  tool = meld
[mergetool "meld"]
  path = meld

# [user]
#   email = <>
#   name = <>

[include]
  path = ~/.config/git-delta.ini
[includeIf "gitdir:~/Documents/work/"]
  path = ~/.config/git/work.conf
