[user]
    name = Max Siryk
    email = maxim.s@radency.com
	  signingkey = AE3F3D82CD2A2610

[core]
    sshCommand = ssh -i ~/.ssh/work/id_ed25519 -o IdentitiesOnly=yes

[commit]
	gpgsign = true

[tag]
	gpgSign = true
