[manager]

prepend_keymap = [
  { on = "l", run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
  { on = [ "g", "r" ], run = '''
    shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
  ''' },
  { on = "T", run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
  { on = "k", run = "plugin --sync arrow --args=-1" },
  { on = "j", run = "plugin --sync arrow --args=1" },

  { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" }
]


[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
