# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/theme-dark.toml
[manager]
border_symbol = " "

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_type  = { fg = "blue" }
perm_exec  = { fg = "blue" }
