# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/theme-dark.toml
[mgr]
border_symbol = " "

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_type  = { fg = "blue" }
perm_exec  = { fg = "blue" }

[tabs]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }
active   = { fg = "black", bg = "blue", bold = true }
inactive = { fg = "blue", bg = "black" }
