[preview]
# Change them to your desired values
max_width  = 1000
max_height = 1000

[mgr]
ratio = [1, 2, 3]
scrolloff = 8

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
