swipe:
  3:
    left:
      command: "xdotool key ctrl+w" # close tab
    right:
      command: "xdotool key shift+ctrl+t" # undo a closed tab
    up:
      command: "xdotool key ctrl+shift+Tab"
    down:
      command: "xdotool key ctrl+Tab"
  4:
    left:
      command: exec i3 workspace prev
    right:
      command: exec i3 workspace next
    up:
      command: exec i3 fullscreen toggle
    down:
      command: exec i3 floating toggle
# pinch:
#   2:
#     in:
#       command: 'xdotool key ctrl+plus'
#     out:
#       command: 'xdotool key ctrl+minus'
#   3:
#     in:
#       command: 'xdotool key ctrl+0'
#     out:
#       command: 'xdotool key ctrl+0'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.4
