# sudo gpasswd -a YOUR_USER input
# echo 'KERNEL=="uinput", GROUP="input", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/input.rules

# echo '
# [Desktop Entry]
# Exec=/home/{user}/Documents/Apps/xremap/xremap-gnome /home/{user}/.config/xremap/config.yml %u
# Version=1.0
# Type=Application
# Categories=Development
# Name=Xremap
# StartupWMClass=xremap
# Terminal=false
# X-GNOME-Autostart-enabled=true
# StartupNotify=true
# ' >> ~/.config/autostart/xremap.desktop

modmap:
  - name: Global
    remap:
      CapsLock:
        held: CapsLock
        alone: Esc
        alone_timeout_millis: 150
      # M_R: CapsLock

default_mode: Insert

virtual_modifiers:
  - CapsLock


shared:
  apps: &apps
    - firefox
    - org.gnome.TextEditor
    - libreoffice-writer


keymap:
  - name: CapsLock
    remap:
      CapsLock-h: [left]
      CapsLock-j: [down]
      CapsLock-k: [up]
      CapsLock-l: [right]

      CapsLock-alt_l-h: [c-left]
      CapsLock-alt_l-j: [down]
      CapsLock-alt_l-k: [up]
      CapsLock-alt_l-l: [c-right]

      CapsLock-0: home
      CapsLock-4: end
      CapsLock-d: [shift-end, c-x]
      CapsLock-alt_l-d: [shift-end, c-x]
      CapsLock-g: [c-backspace]
      CapsLock-alt_l-g: [c-backspace]
      CapsLock-f: [backspace]
      CapsLock-alt_l-f: [backspace]

      CapsLock-p: [shift-0]
      CapsLock-o: [shift-9]
      CapsLock-i: [shift-8]
      CapsLock-u: [shift-7]
      CapsLock-y: [shift-6]
      CapsLock-t: [shift-5]
      CapsLock-r: [shift-4]
      CapsLock-e: [shift-3]
      CapsLock-w: [shift-2]
      CapsLock-q: [shift-1]

      CapsLock-KEY_SEMICOLON: [kpplus]
      CapsLock-alt_l-KEY_SEMICOLON: [minus]

      CapsLock-KEY_APOSTROPHE: [equal]
      CapsLock-alt_l-KEY_APOSTROPHE: [equal]


  - mode: Insert
    application:
      only: *apps
    remap:
      c-leftbrace: [{ set_mode: Normal }, { set_mark: false }]
      CapsLock-v: [{ set_mode: Normal }]

  - mode: Normal
    application:
      only: *apps
    remap:
      # Navigation
      h: { with_mark: left }
      j: { with_mark: down }
      k: { with_mark: up }
      l: { with_mark: right }

      alt_l-h: [alt-h, { set_mark: false }, { set_mode: Insert }]
      alt_l-j: [alt-j, { set_mark: false }, { set_mode: Insert }]
      alt_l-k: [alt-k, { set_mark: false }, { set_mode: Insert }]
      alt_l-l: [alt-l, { set_mark: false }, { set_mode: Insert }]

      # Word navigation
      w: {with_mark: c-right }
      b: {with_mark: c-left }
      e: {with_mark: c-right }

      # Line navigation
      0: {with_mark: home }
      Shift-4: end

      # Page navigation
      Ctrl-u: pageup
      Ctrl-d: pagedown

      # Selecting/Deleting text
      v: { set_mark: true }
      Shift-v: [end, shift-home, { set_mark: true }]
      y: [c-c, { set_mark: false }]
      x: [delete, { set_mark: false }]
      p: [c-v, { set_mark: false }]
      d: [c-x, { set_mark: false }]
      Shift-d: [shift-end, c-x, { set_mark: false }]
      C-Shift-d: [home, shift-end, c-x, { set_mark: false }]

      # Undo and redo
      u: [C-z, { set_mark: false }]
      Ctrl-r: C-Shift-z

      # Insert mode
      i: { set_mode: Insert }
      Shift-i: [home, { set_mode: Insert}]
      a: [{set_mode: Insert}, right]
      Shift-a: [end, { set_mode: Insert}]
      o: [end, enter, { set_mode: Insert}]
      Shift-o: [home, enter, up, { set_mode: Insert}]

      # Tab changes + Alt-Enter simulation
      C-h: c-shift-tab
      C-l: c-tab
      C-j: c-shift-tab
      C-k: c-tab

      # Cancel
      c-leftbrace: [{ set_mark: false }]
