
exec-once = gnome-keyring-daemon --start --components=secrets,ssh
# exec-once = systemctl --user start gnome-keyring-daemon.socket
env = SSH_AUTH_SOCK,/run/user/1000/keyring/ssh

exec-once = slack
exec-once = google-chrome-stable
exec-once = /opt/google/chrome/google-chrome --profile-directory=Default --app-id=mdpkiolbdkhdjpekfbkbmhigcaggjagi
exec-once = /opt/google/chrome/google-chrome --profile-directory=Default --app-id=kjbdgfilnfhdoflbpgamdcdgpehopbep
exec-once = kitty fish -c "~/Documents/work/wingtra/scripts/tmux.fish"

